# Generated by Django 4.1.2 on 2023-12-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ['-id'], 'permissions': (('view_warehouse', 'can view warehouse'),), 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouse'},
        ),
    ]
