# Generated by Django 4.1.2 on 2023-12-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ['company_name'], 'permissions': (('change_company_model', 'can change name of company'),), 'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
    ]
