# Generated by Django 4.1.2 on 2023-12-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_listmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listmodel',
            options={'ordering': ['company_name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
    ]
